---
- name: Intro to Ansible Playbooks
  hosts: all

  tasks:
  - name: This command will change the working directory to somedir/
    ansible.builtin.shell:
      cmd: ansible-galaxy collection install checkpoint.checkpoint
      chdir: /var/lib/awx/projects/anton-awx/
